export const PRODUCTOS = [
  {
    id: "01",
    name: "Expresso",
    price: "$2.500",
    priceDoble: "$4.000",
    img: "https://res.cloudinary.com/dy1ll1azp/image/upload/f_auto,q_auto/v1770346261/expresso_fqzscn.png",
    side: "left",
    deco: "Tip de diseño: El mármol y los tonos oscuros realzan la intensidad del café.",
  },
  {
    id: "02",
    name: "Cappuccino",
    price: "$3.000",
    priceDoble: "$4.000",
    img: "https://res.cloudinary.com/dy1ll1azp/image/upload/f_auto,q_auto/v1770382432/cappu_lhmbw3.png",
    side: "right",
    deco: "Tip de diseño: Las vetas de madera natural crean un entorno de lectura cálido.",
  },
  {
    id: "03",
    name: "Café con leche",
    price: "$3.000",
    priceDoble: "$4.000",
    img: "https://res.cloudinary.com/dy1ll1azp/image/upload/f_auto,q_auto/v1770346262/latte_an4f0a.png",
    side: "left",
    deco: "Tip de diseño: Cerámicas artesanales aportan textura y alma a tu mesa.",
  },
  {
    id: "04",
    name: "Café Cortado",
    price: "$3.000",
    priceDoble: "$4.000",
    img: "https://res.cloudinary.com/dy1ll1azp/image/upload/f_auto,q_auto/v1770346262/latte_an4f0a.png", // Usando palmera temporalmente si no hay foto específica
    side: "right",
    deco: "Tip de diseño: Espacios minimalistas para resaltar el contraste del café.",
  },
  {
    id: "05",
    name: "Té al limón",
    price: "$2.000",
    priceDoble: "$3.500",
    img: "https://res.cloudinary.com/dy1ll1azp/image/upload/f_auto,q_auto/v1770346263/tea_nefvot.png",
    side: "left",
    deco: "Tip de diseño: Luz natural y textiles de lino para un rincón de calma absoluta.",
  },
  {
    id: "06",
    name: "Chocolate",
    price: "$3.000",
    priceDoble: "$4.000",
    img: "https://res.cloudinary.com/dy1ll1azp/image/upload/f_auto,q_auto/v1770381559/choco_n7n78s.png", // Usando juice temporalmente
    side: "right",
    deco: "Tip de diseño: Tonos tierra que invitan a compartir momentos dulces.",
  },
  {
    id: "07",
    name: "Jugo exprimido",
    price: "$3.500",
    img: "https://res.cloudinary.com/dy1ll1azp/image/upload/f_auto,q_auto/v1770346262/juice_inypmr.png",
    side: "left",
    deco: "Tip de diseño: Plantas de hoja ancha refrescan visualmente espacios neutros.",
  },
  {
    id: "08",
    name: "Medialuna",
    price: "$1.000",
    img: "https://res.cloudinary.com/dy1ll1azp/image/upload/f_auto,q_auto/v1770346263/luna_tv8ya5.png",
    side: "right",
    deco: "Tip de diseño: El dorado de la masa destaca sobre platos de piedra volcánica.",
  },
  {
    id: "09",
    name: "Bizcochito",
    price: "$1.000",
    img: "https://res.cloudinary.com/dy1ll1azp/image/upload/f_auto,q_auto/v1770381779/bizcocho_qrcqzt.png", // Usando luna temporalmente
    side: "left",
    deco: "Tip de diseño: Texturas rústicas para un acompañamiento clásico.",
  },
];